### ISSUE TITLE
Django Student Application Requirements Review

### ISSUE THREAD

**Issue by RishikaHaritha** [bvrit-wise-django-team/wise-django-project#16]
hello @pasokan ,

Please review the requirements of Django Student Application, link attached here
https://github.com/bvrit-wise-django-team/wise-django-project/wiki/Student-Application
Thankyou,
Student Application Team

**Comment by vinitha588** [comment]
Hello @pasokan ,

Please review the requirements of Django TPO Application, link attached here
https://github.com/bvrit-wise-django-team/wise-django-project/wiki/Tpo-Application-and-Authentication-Application
Thankyou,
TPO and Authentication Application Team
